pipeline {
    agent {
        docker {
            image 'python:3-alpine'
        }
    }
    stages {
        stage('Build') {
            steps {
                notifyBuild('STARTED')

                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'pip install django'
                    sh 'pip install pymysql'
                    sh 'pip install django-crispy-forms'
                }
            }
        }
        stage('Test') {
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'pip install django_jenkins'
                    sh 'pip install \'coverage==4.5.4\''
                    sh 'pip install pep8'
                    sh 'pip install pyflakes'
                    sh 'pip install pylint'
                    sh 'cd event_manager && python manage.py jenkins --enable-coverage'
                }
            }
            post {
                always {
                    junit 'event_manager/reports/junit.xml'
                    recordIssues(
                        tool: pep8(pattern: 'event_manager/reports/pep8.report'),
                        unstableTotalAll: 200,
                        failedTotalAll: 220
                    )
                    recordIssues(
                        tool: pyLint(pattern: 'event_manager/reports/pylint.report'),
                        unstableTotalAll: 120,
                        failedTotalAll: 220
                    )
                }
                success {
                    notifyBuild('SUCCESS')
                }
                failure {
                    notifyBuild('FAILED')
                }
            }
        }
    }
}

def notifyBuild(String buildStatus = 'STARTED') {
  // build status of null means successful
  buildStatus = buildStatus ?: 'SUCCESS'

  // Default values
  def subject = "${buildStatus}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
  def details = """<p>${buildStatus}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
    <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>"""

  // Send email
  emailext (
        subject: subject,
        body: details,
        to: 'dmytrza@ac.sce.ac.il, michaba6@ac.sce.ac.il, saardi@ac.sce.ac.il, rotemdr@ac.sce.ac.il',
    )
}