# Generated by Django 3.0.5 on 2020-05-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='emailadress',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='firstname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.TextField(),
        ),
    ]
