# Generated by Django 3.0.5 on 2020-05-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200514_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
