# Generated by Django 3.0.4 on 2020-04-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='-', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
