# Generated by Django 3.0.4 on 2020-04-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_updates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updates',
            new_name='CancelledEvents',
        ),
    ]
