# Generated by Django 3.0.4 on 2020-04-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200416_2109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CancelledEvents',
            new_name='CancelledEvent',
        ),
    ]
