# Generated by Django 3.0.5 on 2020-04-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20200416_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventId', models.IntegerField(default=0)),
                ('announcement', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
