# Generated by Django 3.0.5 on 2020-04-16 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_eventupdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventupdates',
            name='EventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
