# Generated by Django 3.0.4 on 2020-04-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20200416_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelledevent',
            name='cancelled',
        ),
        migrations.AlterField(
            model_name='eventupdates',
            name='EventId',
            field=models.IntegerField(default=0),
        ),
    ]
