# Generated by Django 3.0.4 on 2020-05-08 14:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0012_eventcommant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventCommant',
            new_name='EventComment',
        ),
    ]
