# Generated by Django 3.0.5 on 2020-05-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_reportcomment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reportcomment',
            constraint=models.UniqueConstraint(fields=('user', 'EventId', 'CommentId'), name='report_once'),
        ),
    ]
