# Generated by Django 3.0.6 on 2020-05-26 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0016_eventrecommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventId', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('CommentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='choosecomment',
            constraint=models.UniqueConstraint(fields=('user', 'EventId', 'CommentId'), name='choose_once'),
        ),
    ]
